{"level":"error","message":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\connection.js:189:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","timestamp":"2018-02-11T16:18:57.981Z"}
{"level":"error","message":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\connection.js:189:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","timestamp":"2018-02-11T16:25:14.358Z"}
{"level":"error","message":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\connection.js:189:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","timestamp":"2018-02-11T16:25:37.664Z"}
{"level":"error","message":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\connection.js:189:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","timestamp":"2018-02-11T16:27:18.601Z"}
{"level":"error","message":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\connection.js:189:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","timestamp":"2018-02-11T16:27:22.239Z"}
{"level":"error","message":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (C:\\Users\\SaiUmesh\\Desktop\\nodeapps\\express-zero-config\\node_modules\\mongodb-core\\lib\\connection\\connection.js:189:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","timestamp":"2018-02-11T16:27:23.261Z"}
